FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv
RUN pip install pandas
RUN pip install pyarrow
WORKDIR /app
# do stuff here

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy 

COPY [ "starter.py", "./"  ] 

CMD [ "python", "starter.py", "yellow", "2023", "5"]